"use strict"

var HEIGHT_OF_GPS_MAP_SESSION = 0.01//0.002//
var WIDTH_OF_GPS_MAP_SESSION = HEIGHT_OF_GPS_MAP_SESSION
var ZOOM_OF_GPS_MAP_SESSION = 12

exports.USE_LOCAL_SERVER = false

exports.HEIGHT_OF_GPS_MAP_SESSION = HEIGHT_OF_GPS_MAP_SESSION
exports.WIDTH_OF_GPS_MAP_SESSION = WIDTH_OF_GPS_MAP_SESSION
exports.ZOOM_OF_GPS_MAP_SESSION = ZOOM_OF_GPS_MAP_SESSION
